-- 创建商品表
CREATE TABLE IF NOT EXISTS PRODUCT (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    CATEGORY VARCHAR(255),
    PRODUCT_NAME VARCHAR(255),
    PRODUCT_CODE VARCHAR(255) UNIQUE,
    DELIVERY_PRICE DECIMAL(19, 2),
    MAX_RETAIL_PRICE DECIMAL(19, 2),
    MAX_RETAIL_PRICE_PER_KILO DECIMAL(19, 2),
    MEMBER_PRICE_DIFFERENCE DECIMAL(19, 2),
    GROSS_PROFIT_MARGIN DECIMAL(19, 2),
    QUALITY_DESCRIPTION VARCHAR(255),
    ORIGIN VARCHAR(255),
    CREATE_TIME TIMESTAMP,
    UPDATE_TIME TIMESTAMP
);
